version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Password7!
    ports:
      - 5432:5432  